default: &default
  adapter: postgresql
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
  encoding: unicode
  timeout: 5000

development:
  <<: *default
  database: inviter_development

test:
  <<: *default
  database: inviter_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
